
development:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: rubyeffect.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: 199f5ce8afec3be2fe6e56b1c0e60bcc7a0a094b42f298c51c5e4e274dc078aec8df72446d2705f3aa60618ceaf491db3170909b82f004393d3a1a0ccdbecb0b

test:
  secret_key_base: b0cf1cf3d33a1d87c4a59f0b78589a912b0ac7d4df00cb65a5b8f030a7679d260bb0d97e59b7590a7d16d6f8d2802edac8f2223effbdbabfd528fdeeb450c79d

production:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
